### ISSUE TITLE
Erinome UI coloring

### ISSUE THREAD

**Issue by Quickrix** [kriolyth/gv-subway#2]
Раскраска Erinome мешает детектированию входа и клада. Без неё отлично.
Плюс дверь там заменена на букву В
![изображение](https://user-images.githubusercontent.com/22081607/139048771-d6658cd2-1eb4-464b-bdf8-eeb62e776f86.png)

**Comment by kriolyth** [comment]
Спасибо за репорт :) Теперь должно быть получше (#3)
